apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: example-https-default-cert
spec:
  host: example-https-default-cert.apps.training.germanywestcentral.aroapp.io
  to:
    kind: Service
    name: example
  port:
    targetPort: 8000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
